# Разрешаем использование современных библиотек AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Настройки для Kotlin
kotlin.code.style=official

# Увеличиваем память для сборки, чтобы не падало на больших проектах
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Оптимизация размера приложения
android.nonTransitiveRClass=true
